# Generated by Django 4.0.5 on 2022-06-19 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[['P', 'primary'], ['S', 'secondary'], ['D', 'danger']], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
