# Generated by Django 4.0.5 on 2022-06-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[['P', 'primary'], ['S', 'secondary'], ['D', 'danger']], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[['B', 'Beverage'], ['S', 'Snack'], ['M', 'Meal']], max_length=2, null=True),
        ),
    ]
