# Generated by Django 4.0.5 on 2022-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[['P', 'primary'], ['S', 'secondary'], ['D', 'danger']], max_length=10, null=True),
        ),
    ]
