# Generated by Django 4.0.5 on 2022-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='time',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
